version: '3.3'

services:
  howdy:
    image: ${DOCKER_REGISTRY_HOSTNAME}/${DOCKER_IMAGE_NAMESPACE_PROD}/${DOCKER_IMAGE_REPOSITORY}:${DOCKER_IMAGE_TAG}
    deploy:
      placement:
        constraints:
          - node.platform.os == windows
      labels:
        com.docker.lb.hosts: howdy.west.us.se.dckr.org
        com.docker.lb.port: 80
