version: '3.3'

services:
  howdy:
    image: dtr.west.us.se.dckr.org/demo/howdy:${DOCKER_IMAGE_TAG}
    deploy:
      placement:
        constraints:
          - node.platform.os == windows
      labels:
        com.docker.lb.hosts: howdy.west.us.se.dckr.org
        com.docker.lb.port: 80
